# Generated by Django 5.1.4 on 2025-01-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('telefono', models.CharField(max_length=15)),
                ('lista_items', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
