# Generated by Django 5.1.4 on 2025-01-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0002_alter_pedido_options_pedido_estatus_pedido_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='lista_items',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
