# Generated by Django 5.1.4 on 2025-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0003_alter_pedido_lista_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_vendedor',
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_cliente',
            field=models.IntegerField(default=0),
        ),
    ]
