# Generated by Django 5.1.4 on 2025-01-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0005_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('linea', models.CharField(choices=[('inbelleza', 'Inbelleza'), ('barber', 'Barber'), ('platinum', 'Platinum'), ('none', 'None')], default='none', max_length=20)),
            ],
        ),
    ]
