# Generated by Django 5.1.4 on 2025-01-14 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0006_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
