# Generated by Django 5.1.4 on 2025-01-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0007_rename_productos_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='qty_caja',
            field=models.IntegerField(default=0),
        ),
    ]
