# Generated by Django 5.1.4 on 2025-01-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0008_producto_qty_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_3',
            field=models.FloatField(default=0),
        ),
    ]
