# Generated by Django 5.1.4 on 2025-01-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0009_producto_precio_1_producto_precio_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.JSONField(default=dict),
        ),
    ]
