# Generated by Django 5.1.4 on 2025-01-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0010_pedido_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
    ]
