# Generated by Django 5.1.4 on 2025-01-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0011_remove_pedido_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.JSONField(default=dict),
        ),
    ]
