# Generated by Django 5.1.4 on 2025-01-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0015_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
    ]
