# Generated by Django 5.1.2 on 2025-02-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0016_remove_pedido_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_cliente', models.CharField(max_length=255, unique=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de cliente')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='rfc de cliente')),
                ('calle', models.CharField(max_length=255, verbose_name='calle')),
                ('numint', models.CharField(max_length=10, verbose_name='numero interior')),
                ('numext', models.CharField(max_length=10, verbose_name='numero exterior')),
                ('colonia', models.CharField(max_length=255, verbose_name='Nombre de colonia')),
                ('codigo', models.CharField(blank=True, max_length=5, null=True, verbose_name='codigo postal')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre de municipio')),
                ('estado', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre de estado')),
                ('pais', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre pais')),
                ('telefono', models.CharField(blank=True, max_length=255, null=True, verbose_name='numero de telefono')),
                ('clasificacion', models.CharField(choices=[('FORANEO', 'FORANEO'), ('LOCAL', 'LOCAL')], max_length=20)),
                ('curp', models.CharField(blank=True, max_length=18, null=True, verbose_name='curp de cliente')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
    ]
