# Generated by Django 5.1.4 on 2025-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0017_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='calle'),
        ),
    ]
