# Generated by Django 5.1.4 on 2025-02-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0018_alter_client_calle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('FORANEO', 'FORANEO'), ('LOCAL', 'LOCAL')], max_length=20, null=True),
        ),
    ]
