# Generated by Django 5.1.4 on 2025-02-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0019_alter_client_clasificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numext',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='numero exterior'),
        ),
    ]
