# Generated by Django 5.1.4 on 2025-02-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0020_alter_client_numext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='numext',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='numero exterior'),
        ),
        migrations.AlterField(
            model_name='client',
            name='numint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='numero interior'),
        ),
    ]
