# Generated by Django 5.1.4 on 2025-02-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0021_alter_client_numext_alter_client_numint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='rfc de cliente'),
        ),
    ]
