# Generated by Django 5.1.4 on 2025-02-05 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0022_alter_client_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_ventas.client'),
        ),
    ]
