# Generated by Django 5.1.2 on 2025-02-10 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0024_alter_pedido_calle_alter_pedido_codigo_postal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('abierto', 'ABIERTO'), ('en_prograso', 'EN PROGRESO'), ('pendiente', 'ESPERANDO RESPUESTO DE UN TERCERO'), ('resulto', 'RESUELTO'), ('cerrado', 'CERRADO')], default='abierto', max_length=20)),
                ('categoria', models.CharField(choices=[('hardware', 'HARDWARE'), ('software', 'SOFTWARE'), ('wifi', 'WIFI'), ('servidor', 'SERVIDOR'), ('redes', 'REDES'), ('seguridad', 'SEGURIDAD'), ('correo', 'CORREO ELECTRÓNICO'), ('base_de_datos', 'BASE DE DATOS'), ('aplicaciones', 'APLICACIONES ESPECÍFICAS'), ('impresion', 'IMPRESIÓN'), ('telefonia', 'TELEFONÍA/VOIP'), ('soporte_usuario', 'SOPORTE A USUARIOS'), ('backup', 'BACKUP/RECUPERACIÓN')], default='soporte_usuario', max_length=20)),
                ('descripcion', models.TextField()),
                ('nombre_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
