# Generated by Django 5.1.2 on 2025-02-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0026_alter_crearticket_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearticket',
            name='nivel_prioridad',
            field=models.CharField(choices=[('critica', 'Crítica (Alta Prioridad)'), ('alta', 'ALTA'), ('media', 'MEDIA'), ('baja', 'BAJA')], default='baja', max_length=20),
        ),
    ]
