# Generated by Django 5.1.2 on 2025-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0027_crearticket_nivel_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'ABIERTO'), ('en progreso', 'EN PROGRESO'), ('pendiente', 'ESPERANDO RESPUESTO DE UN TERCERO'), ('resuelto', 'RESUELTO'), ('cerrado', 'CERRADO')], default='abierto', max_length=20),
        ),
    ]
