# Generated by Django 5.1.4 on 2025-02-13 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0028_alter_crearticket_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('link_documento', models.URLField(blank=True, max_length=255, null=True)),
                ('tipo_documento', models.CharField(choices=[('PDF', 'PDF'), ('WORD', 'Word'), ('EXCEL', 'Excel'), ('OTRO', 'Otro')], default='PDF', max_length=10)),
                ('publico', models.BooleanField(default=False)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_ventas.area')),
            ],
        ),
    ]
