# Generated by Django 5.1.4 on 2025-02-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0030_remove_directorio_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='nombre',
        ),
        migrations.AddField(
            model_name='directorio',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='area',
            field=models.CharField(choices=[('Administracion', 'Administracion'), ('Asistente', 'Asistente'), ('Cobranza', 'Cobranza'), ('Compras', 'Compras'), ('Produccion', 'Produccion'), ('Ventas', 'Ventas'), ('Rh', 'Rh'), ('Formulaciones', 'Formulaciones'), ('Imagen', 'Imagen'), ('Community', 'Community'), ('Recepcion', 'Recepcion'), ('Calidad', 'Calidad'), ('Proyectos', 'Proyectos'), ('CEO', 'CEO'), ('BLB', 'BLB'), ('Sistemas', 'Sistemas')], default='publica', max_length=20),
        ),
    ]
