# Generated by Django 5.1.2 on 2025-03-26 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0032_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_doc', models.CharField(max_length=20, unique=True)),
                ('doc_sig', models.CharField(blank=True, max_length=20, null=True)),
                ('folio', models.CharField(max_length=20)),
                ('factura', models.CharField(max_length=20)),
                ('cliente_clave', models.CharField(max_length=30)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.CharField(max_length=20)),
                ('nombre_articulo', models.CharField(max_length=100)),
                ('cantidad_solicitada', models.FloatField()),
                ('lote_asignado', models.FloatField(blank=True, max_length=50, null=True)),
                ('cantidad_real', models.FloatField(blank=True, null=True)),
                ('comentaros', models.TextField(blank=True)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='modulo_ventas.factura')),
            ],
        ),
    ]
