# Generated by Django 5.1.4 on 2025-03-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0033_factura_productofactura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productofactura',
            name='lote_asignado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
