# Generated by Django 5.1.4 on 2025-04-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0034_alter_productofactura_lote_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='rfc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
