# Generated by Django 5.1.4 on 2025-04-08 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0035_alter_factura_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_original', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente_clave', models.CharField(max_length=30)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('factura_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_ventas.factura')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_articulo', models.CharField(max_length=20)),
                ('nombre_articulo', models.CharField(max_length=100)),
                ('cantidad_pendiente', models.FloatField()),
                ('lote_asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_real', models.FloatField(blank=True, null=True)),
                ('fecha_surtido', models.DateTimeField(blank=True, null=True)),
                ('backorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='modulo_ventas.backorder')),
            ],
        ),
    ]
