# Generated by Django 5.1.4 on 2025-04-14 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0037_remove_productobackorder_id_articulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backorder',
            name='factura_relacionada',
        ),
        migrations.AddField(
            model_name='backorder',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productobackorder',
            name='codigo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
