# Generated by Django 5.1.4 on 2025-04-21 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0039_remove_backorder_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productobackorder',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_backorder', to='modulo_ventas.backorder'),
        ),
    ]
