# Generated by Django 5.1.4 on 2025-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0040_alter_productobackorder_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='backorder',
            name='check_status',
            field=models.BooleanField(default=False),
        ),
    ]
