# Generated by Django 5.1.4 on 2025-05-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0041_backorder_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='check_status',
            field=models.BooleanField(default=False),
        ),
    ]
