# Generated by Django 5.1.4 on 2025-06-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_ventas', '0042_factura_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backorder',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
